# Generated by Django 5.1.5 on 2025-01-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('dueDate', models.DateTimeField(verbose_name='Due date')),
            ],
        ),
    ]
