# Generated by Django 5.1.5 on 2025-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='userID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
